name: Content Generator Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run blog scraper
        run: python blog_scraper.py
        
      - name: Run image resizer and converter
        run: python resize_convert_images.py
        
      - name: Run image processor
        run: python image_processor.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          
      - name: Run article summarizer
        run: python article_summarizer.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          
      - name: Run content generator
        run: python content_generator.py
        
      - name: Commit changes to this repository
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add content.json processed_images/* processed_articles/* raw_articles/* raw_images/*
          git diff --staged --quiet || git commit -m "Update content and images [skip ci]"
          git push
        
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: affnarayani/legal_advice_test
          token: ${{ secrets.PAT_TOKEN }}
          path: target_repo
          
      - name: Copy content.json to target repository
        run: |
          cp content.json target_repo/content.json
          
      - name: Copy processed images to target repository
        run: |
          mkdir -p target_repo/images
          cp -r processed_images/* target_repo/images/
          
      - name: Commit changes to target repository
        run: |
          cd target_repo
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add content.json images/*
          git diff --staged --quiet || git commit -m "Update content and images [skip ci]"
          git push
          
      - name: Run cleaner
        run: python cleaner.py
        
      - name: Commit cleanup changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add .
          git diff --staged --quiet || git commit -m "Clean up temporary files [skip ci]"
          git push